#!/bin/bash

cd "$(dirname "$0")"

if [ -f ~/.composer/auth.json ]; then
    docker run --rm -t -v `pwd`:/app -v ~/.composer/auth.json:/composer/auth.json --user ${UID}:${GID} d2-hydrator composer $@
else
    docker run --rm -t -v `pwd`:/app --user ${UID}:${GID} d2-hydrator composer $@
fi
